### ISSUE TITLE
Rule IsArray - Add support for custom message

### ISSUE THREAD

**Issue by edcapetti-zz** [Morebec/Validator#15] opened 2020-03-05 13:19 UTC
Rule IsArray doesn't have support for custom message.
> jwillp
> Every rule should support a custom message passed to the constructor as arguments.
> Please add it here as well.

**Comment by jwillp** [comment] 2020-03-05 17:26
Hi @edcaracas, Thank you for contributing.
I am closing since it is a duplicate of #8.
I will review your pull request.

**Closed as completed by jwillp** 2020-03-05 17:26 UTC
Labels: duplicate
